# Generated by Django 3.0.8 on 2021-03-10 11:41

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path),
        ),
        migrations.AddField(
            model_name='ngo',
            name='site',
            field=models.CharField(default='def', max_length=64, verbose_name='Web Site'),
            preserve_default=False,
        ),
    ]
