# Generated by Django 3.1.7 on 2021-03-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210310_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
