# Generated by Django 3.1.7 on 2021-03-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210310_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='year_established',
        ),
    ]
