# Generated by Django 3.1.7 on 2021-03-19 11:30

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210319_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path),
        ),
    ]
