# Generated by Django 3.1.7 on 2021-03-19 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_ngo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='year_established',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
