# Generated by Django 3.1.7 on 2021-03-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_ngo_year_established'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='year_established',
            field=models.DateTimeField(),
        ),
    ]
