# Generated by Django 3.1.7 on 2021-03-19 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210319_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='year_established',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
